pool:
    vmImage: 'macos-latest'
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 6.0.200 SDK'
    inputs:
      packageType: 'sdk'
      version: 6.0.202
  - task: DotNetCoreCLI@2
    displayName: 'Pack Templates'
    inputs:
      packagesToPack: 'Avalonia.Templates.csproj'
      command: pack
      outputDir: '$(Build.ArtifactStagingDirectory)/NuGet'
      verbosityPack: normal
  - task: CmdLine@2
    displayName: 'Install templates'
    inputs:
      script: 'dotnet new -i $(Build.ArtifactStagingDirectory)/NuGet/*.nupkg' 
  - task: CmdLine@2
    displayName: 'Install WASM workload'
    inputs:
      script: 'dotnet workload install --no-cache --disable-parallel ios android wasm-tools --skip-manifest-update --source "https://api.nuget.org/v3/index.json"' 
  - task: PowerShell@2
    displayName: 'Run Tests'
    inputs:
      filePath: 'tests/build-test.ps1'
      failOnStdError: true
      workingDirectory: 'tests'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
      artifactName: 'NuGet'
    condition: succeeded()
